created initial strucutre, implemented the home page, added button co…
ScoreScout/frontend pull request #9
Opened 2023-11-08 11:07 UTC by AhmadAlhussin2

Built the home page. Added initial structure to the project, added button component, and created global styles.

2023-11-08 18:57 UTC, KekStroke requested changes

2023-11-08 18:57 UTC, KekStroke commented on src/theme/GlobalStyle.tsx
> +        box-sizing: border-box;
Maybe link reset.css to the project or paste reset.css code here?

2023-11-10 09:36 UTC, AhmadAlhussin2 commented
Added reset css and fixed button style

2023-11-10 20:40 UTC, KekStroke approved these changes

2023-11-10 20:40 UTC, merged